export { TrainingHeader } from './TrainingHeader'
export { CatchesTab } from './CatchesTab'
export { MapTab } from './MapTab'
export { StatsTab } from './StatsTab'
export { BaitsTab } from './BaitsTab'
export { AddCatchModal } from './AddCatchModal'
export { ManageTakenBaitsModal } from './ManageTakenBaitsModal'
export { TrainingPlanTab } from './TrainingPlanTab'
export { CatchClick } from './CatchClick'
export { MapVisibilityFix } from './MapVisibilityFix'
export { FlyToActiveSegment } from './FlyToActiveSegment'
export { pinIcon, pinLabel } from './PinUtils'
export { AddEventModal } from './AddEventModal'
export { MapClickHandler } from './MapClickHandler'
export { EventsTab } from './EventsTab'
export { EditEventModal } from './EditEventModal'
export { EditCatchModal } from './EditCatchModal'
export { RigTab } from './RigTab'
export { CurrentRigIndicator } from './CurrentRigIndicator'
export { OnWaterPage } from './OnWaterPage'
export { TrainingTips } from './TrainingTips'

// Контекст
export { TrainingProvider, useTrainingContext, useTrainingState, useTrainingActions } from '../context'
export type { TrainingState, CurrentRig, TrainingAction } from '../context'
